spring:
  profiles:
    active: dev
  messages:
    basename: i18n/messages
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 1000
        one-indexed-parameters: true
        size-parameter: pageSize
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.xml
  redis:
    password: ${REDIS_PASSOWRD:password}
  jackson:
    default-property-inclusion: non_null
    mapper:
      accept_case_insensitive_properties: true
    deserialization:
      fail-on-unknown-properties: false

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:/mapper/*/*.xml,classpath:mapper/*.xml
mapper:
  wrap-keyword: '`{0}`'


logging:
  level:
    com.megaease: debug

template:
  security:
    secret-key: ${SECURITY_KEY:iQCfwM6Zl12b7T2CjPK3ZFaVFWqoydF1cDnQyb5ed20=}
    allowed-origins:
      - '*'
server:
  port: 37080